#ifndef STSCONFIG_H_
#define STSCONFIG_H_

#define STSCONFIG_FILENAME "@STSCONFIG_FILENAME@"
#define STS_VERSION "@CPACK_PACKAGE_VERSION_MAJOR@.@CPACK_PACKAGE_VERSION_MINOR@"
#define STS_REVISION_VERSION "@Project_WC_REVISION@"
#endif /*STSCONFIG_H_*/
